apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-file-upload  # Changed from 'quick_file_upload' to 'quick-file-upload'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quick-file-upload  # Changed from 'quick_file_upload' to 'quick-file-upload'
  template:
    metadata:
      labels:
        app: quick-file-upload  # Changed from 'quick_file_upload' to 'quick-file-upload'
    spec:
      containers:
      - name: quick-file-upload-container  # Changed from 'quick_file_upload' to 'quick-file-upload-container'
        image: quick_file_upload:latest
        ports:
        - containerPort: 8083
        volumeMounts:
        - mountPath: /app/upload
          name: upload-volume
      volumes:
      - name: upload-volume
        hostPath:
          path: /home/iabhilashjoshi/uploaded_files
          type: Directory
