apiVersion: v1
kind: Service
metadata:
  name: quick_file_upload
spec:
  selector:
    app: my-quick_file_upload
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer # or use 'NodePort' if not on a cloud provider
