apiVersion: v1
kind: Service
metadata:
  name: quick-file-upload  # Changed from 'quick_file_upload' to 'quick-file-upload'
spec:
  selector:
    app: quick-file-upload  # Changed from 'quick_file_upload' to 'quick-file-upload'
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer  # Use 'NodePort' if not on a cloud provider
